version: '3.8'

services:
  app:
    image: php-laravel:8.3
    container_name: laravel-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    working_dir: /var/www/html
    command: apache2-foreground

  db:
    image: mysql:8
    container_name: laravel-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ordertracking
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"

volumes:
  db-data:
